# Generated by Django 3.1.1 on 2020-11-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20201110_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='played',
            field=models.BooleanField(default=True),
        ),
    ]
