# Generated by Django 3.1.1 on 2020-11-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='api_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
