# Generated by Django 3.1.1 on 2020-11-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20201105_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotion',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Emotion',
        ),
    ]
