# Generated by Django 3.1.1 on 2020-11-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20201106_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='clip',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
